### ISSUE TITLE
Not available in my country !

### ISSUE THREAD

**Issue by sonalder-darlene** [C-Rodg/Pomobaro#1]
You app looks nice and I want it... but it's not available in my country (Switzerland)!
Also I would like to have a direct download or a GitHub release to not rely on the Apple App Store for downloading this app.
Could you send me a zip or dmg or something ?

Thanks,
Sonalder

**Comment by C-Rodg** [comment]
Hello! Thank you for your interest in Pomobaro.  Unfortunately, I no longer have the time to support this project, so it has been discontinued and removed from the app store.  I appreciate your interest though!
